# Generated by Django 4.0.1 on 2022-01-21 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название бригады')),
                ('dateOfForming', models.DateField(verbose_name='Дата формирования')),
            ],
            options={
                'verbose_name': 'Бригада',
                'verbose_name_plural': 'Бригады',
            },
        ),
        migrations.CreateModel(
            name='Fire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('dateOfFire', models.DateField(verbose_name='Дата пожара')),
                ('timeOfArrival', models.DateTimeField(verbose_name='Время прибытия')),
                ('brigadeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brigade', verbose_name='Номер пригады')),
            ],
            options={
                'verbose_name': 'Пожар',
                'verbose_name_plural': 'Пожары',
            },
        ),
        migrations.CreateModel(
            name='FireEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('brand', models.CharField(max_length=20, verbose_name='Бренд')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('typeOfFireFight', models.CharField(max_length=50, verbose_name='Тип пожаротушения')),
            ],
            options={
                'verbose_name': 'Пожарная машина',
                'verbose_name_plural': 'Пожарные машины',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=70, verbose_name='Адрес')),
                ('typeOfObject', models.CharField(max_length=70, verbose_name='Тип объекта')),
                ('square', models.IntegerField(default=100, verbose_name='Площадь')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='ReasonOfFire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Причина пожара',
                'verbose_name_plural': 'Причины пожара',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=70, verbose_name='Полное имя')),
                ('dateOfBirth', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(max_length=5, verbose_name='Пол')),
                ('position', models.CharField(max_length=30, verbose_name='Должность')),
                ('brigadeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brigade', verbose_name='Номер бригады')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Injured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=70, verbose_name='Полное имя')),
                ('dateOfBirth', models.DateField(verbose_name='Дата рождения')),
                ('damage', models.CharField(max_length=100, verbose_name='Повреждения')),
                ('fireId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fire', verbose_name='Номер пожара')),
            ],
            options={
                'verbose_name': 'Пострадавший',
                'verbose_name_plural': 'Пострадавший',
            },
        ),
        migrations.AddField(
            model_name='fire',
            name='fireCarId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fireengine', verbose_name='Номер пожарной машины'),
        ),
        migrations.AddField(
            model_name='fire',
            name='objectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.object', verbose_name='Номер объекта'),
        ),
        migrations.AddField(
            model_name='fire',
            name='reasonId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reasonoffire', verbose_name='Номер причины'),
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=30, verbose_name='Кодовое название')),
                ('fireId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fire', verbose_name='Номер пожара')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
            },
        ),
    ]
