# Generated by Django 4.0.1 on 2022-01-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название статьи')),
                ('blogRecord', models.CharField(max_length=200, verbose_name='Запись блога')),
                ('nameOfWriter', models.CharField(max_length=70, verbose_name='Имя редактора')),
            ],
            options={
                'verbose_name': 'Запись блога',
                'verbose_name_plural': 'Записи блога',
            },
        ),
    ]
