# Generated by Django 4.0.1 on 2022-01-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heahhunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=70, verbose_name='ФИО')),
                ('dateOfBirth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Отзыв соискателя',
                'verbose_name_plural': 'Отзывы соискателей',
            },
        ),
    ]
