# Generated by Django 4.0.1 on 2022-04-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_heahhunt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakedSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('compound', models.CharField(max_length=200, verbose_name='Состав')),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Запечённый сет',
                'verbose_name_plural': 'Запечённые сеты',
            },
        ),
        migrations.CreateModel(
            name='ClassicSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('compound', models.CharField(max_length=200, verbose_name='Состав')),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Классический сет',
                'verbose_name_plural': 'Классические сеты',
            },
        ),
        migrations.CreateModel(
            name='ComboSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('compound', models.CharField(max_length=200, verbose_name='Состав')),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Комбо сет',
                'verbose_name_plural': 'Комбо сеты',
            },
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='call',
            name='fireId',
        ),
        migrations.RemoveField(
            model_name='fire',
            name='brigadeId',
        ),
        migrations.RemoveField(
            model_name='fire',
            name='fireCarId',
        ),
        migrations.RemoveField(
            model_name='fire',
            name='objectId',
        ),
        migrations.RemoveField(
            model_name='fire',
            name='reasonId',
        ),
        migrations.DeleteModel(
            name='Heahhunt',
        ),
        migrations.RemoveField(
            model_name='injured',
            name='fireId',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='brigadeId',
        ),
        migrations.DeleteModel(
            name='Brigade',
        ),
        migrations.DeleteModel(
            name='Call',
        ),
        migrations.DeleteModel(
            name='Fire',
        ),
        migrations.DeleteModel(
            name='FireEngine',
        ),
        migrations.DeleteModel(
            name='Injured',
        ),
        migrations.DeleteModel(
            name='Object',
        ),
        migrations.DeleteModel(
            name='ReasonOfFire',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
