# Generated by Django 4.0.1 on 2022-05-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakedSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('compound', models.CharField(max_length=200, verbose_name='Состав')),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Запечённый ролл',
                'verbose_name_plural': 'Запечённые роллы',
            },
        ),
        migrations.CreateModel(
            name='Deserts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('compound', models.CharField(max_length=200, verbose_name='Состав')),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Десерт',
                'verbose_name_plural': 'Десерты',
            },
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('compound', models.CharField(max_length=200, verbose_name='Состав')),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Напитки',
            },
        ),
        migrations.CreateModel(
            name='HotAndSalads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('compound', models.CharField(max_length=200, verbose_name='Состав')),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Горячее и салаты',
                'verbose_name_plural': 'Горячее и салаты',
            },
        ),
        migrations.CreateModel(
            name='MagRolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('compound', models.CharField(max_length=200, verbose_name='Состав')),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Маг ролл',
                'verbose_name_plural': 'Маг роллы',
            },
        ),
        migrations.CreateModel(
            name='MiniRolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('compound', models.CharField(max_length=200, verbose_name='Состав')),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Мини ролл',
                'verbose_name_plural': 'Мини роллы',
            },
        ),
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('compound', models.CharField(max_length=200, verbose_name='Состав')),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Набор',
                'verbose_name_plural': 'Наборы',
            },
        ),
        migrations.CreateModel(
            name='Soup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('compound', models.CharField(max_length=200, verbose_name='Состав')),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Суп',
                'verbose_name_plural': 'Супы',
            },
        ),
        migrations.CreateModel(
            name='SushiStuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('compound', models.CharField(max_length=200, verbose_name='Состав')),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Все для суши',
                'verbose_name_plural': 'Все для суши',
            },
        ),
        migrations.CreateModel(
            name='Tempured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('compound', models.CharField(max_length=200, verbose_name='Состав')),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Темпур',
                'verbose_name_plural': 'Темпура',
            },
        ),
        migrations.CreateModel(
            name='Vegan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('compound', models.CharField(max_length=200, verbose_name='Состав')),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Вег меню',
                'verbose_name_plural': 'Вег меню',
            },
        ),
    ]
