# Generated by Django 4.0.3 on 2022-05-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_classicset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classicset',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\images'),
        ),
    ]
