# Generated by Django 4.0.3 on 2022-05-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_pizza_pricel_pizza_pricem_pizza_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakedset',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\images'),
        ),
        migrations.AddField(
            model_name='bakedsets',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\images'),
        ),
        migrations.AddField(
            model_name='comboset',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\images'),
        ),
        migrations.AddField(
            model_name='deserts',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\images'),
        ),
        migrations.AddField(
            model_name='drinks',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\images'),
        ),
        migrations.AddField(
            model_name='hotandsalads',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\images'),
        ),
        migrations.AddField(
            model_name='magrolls',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\images'),
        ),
        migrations.AddField(
            model_name='minirolls',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\images'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\images'),
        ),
        migrations.AddField(
            model_name='rolls',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\images'),
        ),
        migrations.AddField(
            model_name='sets',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\images'),
        ),
        migrations.AddField(
            model_name='soup',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\images'),
        ),
        migrations.AddField(
            model_name='sushi',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\images'),
        ),
        migrations.AddField(
            model_name='sushistuff',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\images'),
        ),
        migrations.AddField(
            model_name='tempured',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\images'),
        ),
        migrations.AddField(
            model_name='vegan',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\images'),
        ),
        migrations.AddField(
            model_name='wok',
            name='image',
            field=models.ImageField(null=True, upload_to='static\\images'),
        ),
    ]
