# Generated by Django 4.0.3 on 2022-05-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_bakedset_image_bakedsets_image_comboset_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='static\\images')),
                ('type', models.CharField(choices=[('СШ', 'Суши'), ('РЛ', 'Роллы'), ('ЗР', 'Запечённые роллы'), ('НБ', 'Наборы'), ('ТП', 'Темпура'), ('ЛВ', 'Лапша wok'), ('СП', 'Супы'), ('ГС', 'Горячее и салаты'), ('МР', 'Мини роллы'), ('МГР', 'Маг роллы'), ('ВМ', 'Вегетарианское меню'), ('ДС', 'Десерты'), ('НП', 'Напитки'), ('ВС', 'Всё для суши'), ('ПЦ', 'Пицца')], max_length=40, verbose_name='Тип товара')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('compound', models.CharField(max_length=200, verbose_name='Состав')),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.DeleteModel(
            name='BakedSet',
        ),
        migrations.DeleteModel(
            name='BakedSets',
        ),
        migrations.DeleteModel(
            name='ComboSet',
        ),
        migrations.DeleteModel(
            name='Deserts',
        ),
        migrations.DeleteModel(
            name='Drinks',
        ),
        migrations.DeleteModel(
            name='HotAndSalads',
        ),
        migrations.DeleteModel(
            name='MagRolls',
        ),
        migrations.DeleteModel(
            name='MiniRolls',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Rolls',
        ),
        migrations.DeleteModel(
            name='Sets',
        ),
        migrations.DeleteModel(
            name='Soup',
        ),
        migrations.DeleteModel(
            name='Sushi',
        ),
        migrations.DeleteModel(
            name='SushiStuff',
        ),
        migrations.DeleteModel(
            name='Tempured',
        ),
        migrations.DeleteModel(
            name='Vegan',
        ),
        migrations.DeleteModel(
            name='Wok',
        ),
    ]
