# Generated by Django 4.0.3 on 2022-05-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_delete_bakedset_delete_bakedsets_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassicSet',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
