# Generated by Django 4.0.3 on 2022-05-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_classicset_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Суши', 'Суши'), ('Роллы', 'Роллы'), ('Запечённые роллы', 'Запечённые роллы'), ('Наборы', 'Наборы'), ('Темпура', 'Темпура'), ('Лапша wok', 'Лапша wok'), ('Супы', 'Супы'), ('Горячее и салаты', 'Горячее и салаты'), ('Мини роллы', 'Мини роллы'), ('Маг роллы', 'Маг роллы'), ('Вегетарианское меню', 'Вегетарианское меню'), ('Десерты', 'Десерты'), ('Напитки', 'Напитки'), ('Всё для суши', 'Всё для суши'), ('Пицца', 'Пицца')], max_length=40, verbose_name='Тип товара'),
        ),
    ]
